version: '3.9' 
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "waveifydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "558899ASE2005"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend  # Контекст сборки указывает на папку Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro  
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  postgres-data: