events {}

http {
    server {
        listen 80;
        server_name waveify.ru www.waveify.ru;  # Указываем домен

        # Прокси для API
        location /api {
            proxy_pass http://backend:5000;  # Здесь backend - это имя сервиса в docker-compose или контейнера
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'keep-alive';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;  # Добавлено для передачи IP клиента
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Тоже для передачи оригинального IP
            proxy_set_header X-Forwarded-Proto $scheme;  # Передача схемы протокола (http/https)
        }

        # Прокси для фронтенда
        location / {
            proxy_pass http://frontend:3000;  # Здесь frontend - это имя сервиса в docker-compose или контейнера
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'keep-alive';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;  # Добавлено для передачи IP клиента
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Тоже для передачи оригинального IP
            proxy_set_header X-Forwarded-Proto $scheme;  # Передача схемы протокола (http/https)
        }
    }
}
